### ISSUE TITLE
website is not opening

### ISSUE THREAD

**Issue by Dilpreet-Sandhu** [RishiBakshii/mern-chat-e2ee#5]
your website is not opening

![Screenshot 2024-11-21 165844](https://github.com/user-attachments/assets/e1158f39-f10c-4f26-a386-c65211eba01e)

**Comment by RishiBakshii** [comment]
hi @Dilpreet-Sandhu thanks for raising an issue, actually my hostinger plan is expired so that is why website is not openning, i am planning to host the frontend on aws, so it will be fixed in no time :)

**Comment by Dilpreet-Sandhu** [comment]
ok

**Comment by RishiBakshii** [comment]
hi @Dilpreet-Sandhu now i have re-hosted this on a different domain https://mernchat.in , now you can visit the webapp and don't forget to send me a friend request there :) 

closing the issue now
